### ISSUE TITLE
デジタル、デジタル以外を一括でダウンロードできない

### ISSUE THREAD

**Issue by sakuemon** [furyutei/amzOrderHistoryFilter#1]
便利なプラグインですね！毎年、この時期になると困っていたのですが、今回から楽ができそうです。

さて、使ってみたのですが、デジタル、デジタル以外のチェックボックスを両方つけたとき、デジタルだけが対象になっているようです。

バージョン：0.1.0.1501
chrome版です。

**Comment by furyutei** [comment]
ご利用ありがとうございます。
両方のチェックボックスを付けた場合、[デジタル用のタブとデジタル以外のが二つ開くようになっている](https://memo.furyutei.work/entry/amzOrderHistoryFilter#%E4%BD%BF%E3%81%84%E6%96%B9)のですが（元となる領収書ページのHTML構造が随分違っているので、同一タブ上に表示するのが困難なため）、それが一つしか開かないということでしょうか？

**Comment by sakuemon** [comment]
勘違いしてました。タブが２つ開いて、それぞれでダウンロードするんですね。
それでしたら問題ないようです。
