### ISSUE TITLE
デジタル以外のクレジットカード種類の表示はできないでしょうか？

### ISSUE THREAD

**Issue by no1-knows** [furyutei/amzOrderHistoryFilter#3]
税理士さんからアマゾンの履歴を出してといわれて、見つかったのがこのフィルターでした。
非常に便利なプラグインをありがとうございます！

デジタル以外のクレジットカード種類が表示されなかったのですが、表示するための設定などはありますか？
デジタルの履歴には、クレジットカード情報が表示されています。

クレジットカードの番号で、個人と法人を分けているため、ソートできると非常に嬉しいです。
どうぞよろしくお願いいたします。

**Comment by furyutei** [comment]
ご報告ありがとうございます。

調べてみたところ、クレカ情報だけではなく、「商品小計」～「クレカ」列がおかしくなっています。
これは、いつの間にか Amazon.co.jp 様の領収書のフォーマットが変わってしまい、うまく情報が取得できなくなったためのようです。
※[関連ツイート](https://twitter.com/furyutei/status/1184765369702944769)

現在検討中ですが、対応は難しいかも知れません……。

**Comment by no1-knows** [comment]
ご確認ありがとうございます。
ツイートを拝見させていただきましたが、かなりランダムな表記なので対応が難しそうですね。

僕のような要望は少数なはずなので、誰かが良いアイデアをだしてくれるのを期待する形で良いかと思います。

それ以外のデータを簡単に取得できるだけでも本当に助かりました。
改めてありがとうございます！

**Comment by furyutei** [comment]
[ある程度割り切って対応してみましたので](https://github.com/furyutei/amzOrderHistoryFilter/commit/21df67d7d2dd325e62ed4a67b585101840fd2db1)、よろしければお試しください。
※[対応内容の詳細はこちら](https://twitter.com/furyutei/status/1185132871943622659)

**Comment by no1-knows** [comment]
早急な対応をありがとうございます！
作業がはかどり助かりました。
