### ISSUE TITLE
デジタル領収書のcsv出力ができません…

### ISSUE THREAD

**Issue by shuny59** [furyutei/amzOrderHistoryFilter#4]
素晴らしいプラグインありがとうございます。日々活用させていただいております！
今までは問題なかったのですが、数週間前にデジタル領収書のcsv出力をしようとしたところ、csvファイルに項目名しか表示されなくなってしまいました…。こちら使い方に問題があるのでしょうか？

**Comment by furyutei** [comment]
ご報告ありがとうございます。
こちらはデジタルの領収書のHTML構造が変更されたことに伴う不具合かと思われます。
[バージョン 0.1.0.2501](https://github.com/furyutei/amzOrderHistoryFilter/commit/3ad09e08cbbd79bebdaf4100a32ea2ea1012364a) で対応しましたので、ご確認いだだけますでしょうか。

**Comment by shuny59** [comment]
出力されました！
あっという間に修正いただき、大変ありがとうございます。

これからも利用&布教させていただきます！


2020年10月7日(水) 13:06 風柳 (furyu) <notifications@github.com>:
